const lang={

  en:{
    search:"Search",
    placeholder1:"Search Here",
    placeholder2:"E-mail/Mobile Number",
    placeholder3:"Password",
    signout:"Sign Out",
    gbt:"A.I",
    home:"Home",
    signin:"Sign In",
    signup:"Sign Up",
    signup1:"SignUp Now",
    play:"Play",
    moreinfo:"More Info",
    upcoming:"Upcoming",
    nowplaying:"Now Playing",
    toprated:"Top Rated",
    popular:"Popular",
    classics:"Classics",
    animeandfantasy:"Anime and Fantasy",
    comedydrama:"Comedy and Drama",
    starring:"Starring Di-Caprio",
    ntnf:"New to Netflix?",
    content1:"Unlimited movies,TV shows and more",
    content2:"Watch Anywhere,cancel anytime",
    content3:"Ready to watch? Enter your email or mobile number to create or restart your membership.",
    aha:"Already Have Account?",
    language:"English",
    gs:"GET STARTED",
    ema:"E-mail",
    SWM:"So,What's your mood right now?",
    load:"Loading..."

  },

  tm:{
    search:"தேடு",
    placeholder1:"இங்கே தேடவும்.....",
    placeholder2:"மின்னஞ்சல்/மொபைல் எண்",
    placeholder3:"கடவுச்சொல்",
    signout:"வெளியேறு",
    gbt:"ஏ.ஐ",
    home:"முகப்பு",
    signin:"உள்நுழைக",
    signup:"பதிவு செய்யவும்",
    play:"இயக்கு",
    moreinfo:"மேலும்",
    upcoming:"விரைவில்",
    nowplaying:"திரையில்",
    toprated:"சிறந்தவை",
    popular:"பிரபலமான",
    classics:"கிளாசிக்",
    animeandfantasy:"அனிமே மற்றும் பேண்டஸி",
    comedydrama:"நகைச்சுவை மற்றும் நாடகம்",
    starring:"டி-கேப்ரியோ நடிப்பில்",
    ntnf:"சந்தாதாரர் அல்ல?",
    content1:"வரம்பற்ற திரைப்படங்கள், டிவி நிகழ்ச்சிகள் மற்றும் பல",
    content2:"எங்கும் பார்க்கவும், எப்போது வேண்டுமானாலும் ரத்து செய்யாலம்",
    content3:"பார்க்கத் தயாரா? உங்கள் மெம்பர்ஷிப்பை உருவாக்க அல்லது மறுதொடக்கம் செய்ய உங்கள் மின்னஞ்சல் அல்லது மொபைல் எண்ணை உள்ளிடவும்.",
    aha:"சந்தாதாரரா?",
    language:"தமிழ்",
    gs:"ஆரம்பிக்களாங்களா?",
    ema:"மின்னஞ்சல்",
    SWM:"எனவே, இப்போது உங்கள் மனநிலை?",
    load:"காத்திருக்க...."

  }
}
export default lang